{
    'name': 'DVIT SMARTSYS Report ',
    'summary': 'SMARTSYS Report',
    'version': '10.0.1.0',
    'category': 'Sales',
    'license': 'AGPL-3',
    'author': "DVIT.ME",
    'website': 'http://dvit.me/',
    "price": 500.0,
    "currency": 'EUR',
    'depends': [
        'product_pack',
        'partner_contact_department',
        'dvit_sale_discount',
        'sales_report_product_image',
        'dvit_sale_hide_price',
        'dvit_sale_duplicate_lines',
       'dvit_sale_option_lines',
       'dvit_sale_alt_product',
       'dvit_sale_line_no',
        ],
    'data': [
        'views/views.xml',
        'views/templates.xml',
    ],
    'installable': True,
}
